#pragma once

#define HAL_DMA2D_MODULE_ENABLED
#define HAL_RNG_MODULE_ENABLED
#define HAL_HASH_MODULE_ENABLED
#define HAL_CRC_MODULE_ENABLED
#define HAL_RIF_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
#define HAL_RTC_MODULE_ENABLED
#define HAL_TIM_MODULE_ENABLED
#define HAL_LTDC_MODULE_ENABLED
#define HAL_DCMIPP_MODULE_ENABLED
#include_next "stm32n6xx_hal_conf.h"