"""Emit the C++ header consumed by kernel/middleware/ui from a Layout."""

from __future__ import annotations

from .schema import Layout, parse_color, pascal_case


def _rgb(color: str) -> str:
    red, green, blue = parse_color(color)
    return f"ui::Rgb565(0x{red:02X}U, 0x{green:02X}U, 0x{blue:02X}U)"


def _cpp_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate_header(layout: Layout, source_name: str) -> str:
    lines = [
        f"// Generated by host_app/ui_designer from {source_name}. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "middleware/ui/widget.hpp"',
        "",
        f"namespace {layout.namespace} {{",
        "",
        f"inline constexpr std::uint16_t kScreenWidth = {layout.width}U;",
        f"inline constexpr std::uint16_t kScreenHeight = {layout.height}U;",
        "",
        "enum class WidgetId : std::uint16_t {",
    ]
    for index, widget in enumerate(layout.widgets, start=1):
        lines.append(f"    k{pascal_case(widget.id)} = {index}U,")
    lines += ["};", ""]

    if layout.widgets:
        lines.append("inline constexpr ui::ButtonSpec kButtons[] = {")
        for widget in layout.widgets:
            style = widget.style
            lines += [
                "    {",
                f"        static_cast<std::uint16_t>(WidgetId::k{pascal_case(widget.id)}),",
                f"        {{{widget.x}U, {widget.y}U, {widget.width}U, {widget.height}U}},",
                f"        {_cpp_string(widget.label)},",
                "        {",
                f"            {_rgb(style.fill)},",
                f"            {_rgb(style.pressed_fill)},",
                f"            {_rgb(style.border)},",
                f"            {_rgb(style.text)},",
                f"            {style.text_scale}U,",
                f"            {style.border_width}U,",
                "        },",
                "    },",
            ]
        lines += [
            "};",
            "inline constexpr std::size_t kButtonCount =",
            "    sizeof(kButtons) / sizeof(kButtons[0]);",
        ]
    else:
        lines += [
            "inline constexpr const ui::ButtonSpec *kButtons = nullptr;",
            "inline constexpr std::size_t kButtonCount = 0U;",
        ]
    lines += _dispatch(layout)
    lines += [
        "",
        f"}} // namespace {layout.namespace}",
        "",
    ]
    return "\n".join(lines)


_EVENT_TYPES = {"on_tap": "kTap", "on_press": "kPress"}


def _dispatch(layout: Layout) -> list[str]:
    """Route events to handler methods named in the layout.

    Handlers is any type with `void <name>(const ui::Event &)` methods; a
    missing method is a compile error at the application's call site.
    """
    handlers = sorted({
        getattr(w, event) for w in layout.widgets for event in _EVENT_TYPES
        if getattr(w, event)})
    lines = [
        "",
        "/* Handler methods the application must provide on its Handlers type:",
    ]
    lines += [f" *   void {name}(const ui::Event &event);" for name in handlers] or [" *   (none)"]
    lines += [
        " */",
        "template <typename Handlers>",
        "bool Dispatch(Handlers &handlers, const ui::Event &event)",
        "{",
    ]
    cases_emitted = False
    for event, enum_name in _EVENT_TYPES.items():
        bound = [(w, getattr(w, event)) for w in layout.widgets if getattr(w, event)]
        if not bound:
            continue
        cases_emitted = True
        lines += [
            f"    if (event.type == ui::EventType::{enum_name}) {{",
            "        switch (static_cast<WidgetId>(event.widget_id)) {",
        ]
        for widget, handler in bound:
            lines += [
                f"        case WidgetId::k{pascal_case(widget.id)}:",
                f"            handlers.{handler}(event);",
                "            return true;",
            ]
        lines += [
            "        default:",
            "            break;",
            "        }",
            "    }",
        ]
    if not cases_emitted:
        lines += ["    (void)handlers;", "    (void)event;"]
    lines += ["    return false;", "}"]
    return lines
