"""Emit YAML, C++ headers, and the linker script from resolved JSON."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .common import (
    LayoutError,
    generate_memory_regions,
    generate_key_header,
    generate_raw_header,
    generate_static_sections,
    normalize_layout,
    write_if_changed,
)


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_./:-]*", text) and text.lower() not in {
        "true",
        "false",
        "null",
        "yes",
        "no",
    }:
        return text
    return json.dumps(text, ensure_ascii=False)


def _dump_yaml(value: Any, indent: int = 0) -> list[str]:
    prefix = " " * indent
    lines: list[str] = []
    if isinstance(value, dict):
        for key, child in value.items():
            if isinstance(child, (dict, list)):
                lines.append(f"{prefix}{key}:")
                lines.extend(_dump_yaml(child, indent + 2))
            else:
                lines.append(f"{prefix}{key}: {_yaml_scalar(child)}")
    elif isinstance(value, list):
        for child in value:
            if isinstance(child, dict):
                if not child:
                    lines.append(f"{prefix}- {{}}")
                    continue
                first = True
                for key, nested in child.items():
                    marker = f"{prefix}- " if first else f"{prefix}  "
                    first = False
                    if isinstance(nested, (dict, list)):
                        lines.append(f"{marker}{key}:")
                        lines.extend(_dump_yaml(nested, indent + 4))
                    else:
                        lines.append(f"{marker}{key}: {_yaml_scalar(nested)}")
            elif isinstance(child, list):
                lines.append(f"{prefix}-")
                lines.extend(_dump_yaml(child, indent + 2))
            else:
                lines.append(f"{prefix}- {_yaml_scalar(child)}")
    return lines


def generate_yaml(document: dict[str, Any]) -> str:
    return "\n".join(_dump_yaml(document)) + "\n"


def generate_memory_config(document: dict[str, Any]) -> str:
    policy = document["allocator_policy"]
    derived = document["derived"]
    alignment = int(policy["alignment"])
    outputs = [int(value) for value in derived["inference_output_bytes"]]
    output_values = ", ".join(f"{value}U" for value in outputs)
    return "\n".join(
        [
            "/* Generated by host_app/auto_static_memory_layout. Do not edit. */",
            "",
            "#ifndef UAI_AI_MEMORY_MANAGER_MEMORY_CONFIG_HPP",
            "#define UAI_AI_MEMORY_MANAGER_MEMORY_CONFIG_HPP",
            "",
            "#include <array>",
            "#include <cstddef>",
            "",
            "namespace uai::ai::memory_manager {",
            "",
            "struct MemoryConfig {",
            f"    std::size_t buffer_alignment = {alignment}U;",
            "    std::array<std::size_t, "
            f"{len(outputs)}U> model_output_bytes = {{{output_values}}};",
            "",
            "    constexpr std::size_t AlignUp(std::size_t value) const",
            "    {",
            "        return (value + buffer_alignment - 1U) /",
            "               buffer_alignment * buffer_alignment;",
            "    }",
            "",
            "    constexpr std::size_t inference_output_storage_bytes() const",
            "    {",
            "        std::size_t total = 0U;",
            "        for (const std::size_t output_bytes : model_output_bytes) {",
            "            total += AlignUp(output_bytes);",
            "        }",
            "        return total;",
            "    }",
            "};",
            "",
            "inline constexpr MemoryConfig kMemoryConfig{};",
            f"inline constexpr std::size_t kCaptureBufferCount = {int(policy['capture_count'])}U;",
            f"inline constexpr std::size_t kDisplayBufferCount = {int(policy['display_count'])}U;",
            f"inline constexpr std::size_t kInferenceBufferCount = {int(policy['inference_count'])}U;",
            f"inline constexpr std::size_t kInferenceSourceBufferCount = {int(policy['inference_source_count'])}U;",
            "",
            "} // namespace uai::ai::memory_manager",
            "",
            "#endif",
            "",
        ]
    )


def _replace_braced_block(text: str, start_pattern: str, replacement: str) -> str:
    match = re.search(start_pattern, text, re.MULTILINE)
    if not match:
        raise LayoutError(f"linker script is missing {start_pattern!r}")
    brace_start = text.find("{", match.start(), match.end() + 1)
    if brace_start < 0:
        raise LayoutError("linker script block has no opening brace")
    depth = 0
    for index in range(brace_start, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[: match.start()] + replacement + text[index + 1 :]
    raise LayoutError("unterminated linker script block")


def _remove_linker_sections(text: str, sections: set[str]) -> str:
    for section in sections:
        pattern = re.compile(
            rf"^  \.{re.escape(section)}(?:\s+\(NOLOAD\))?\s*"
            r"(?:0x[0-9A-Fa-f]+\s*)?:\s*\n"
            r"  \{.*?^  \}\s*>[A-Za-z_][A-Za-z0-9_]*\s*\n",
            re.MULTILINE | re.DOTALL,
        )
        text, count = pattern.subn("", text, count=1)
        if count != 1:
            raise LayoutError(f"linker script is missing generated section .{section}")
    return text


def generate_linker(document: dict[str, Any], base_path: Path) -> str:
    layout = normalize_layout(document)
    text = base_path.read_text(encoding="utf-8")
    text = _replace_braced_block(
        text,
        r"^MEMORY\s*\{",
        "MEMORY\n{\n" + generate_memory_regions(layout) + "\n}",
    )
    entry = document.get("linker", {}).get("entry")
    if entry:
        text = re.sub(
            r"^ENTRY\([^\n]+\)",
            f"ENTRY({entry})",
            text,
            count=1,
            flags=re.MULTILINE,
        )

    sections = {allocation["section"] for allocation in layout["allocations"]}
    text = _remove_linker_sections(text, sections)
    app_allocations = [
        allocation for allocation in layout["allocations"] if allocation["memory"] == "APP"
    ]
    external_allocations = [
        allocation for allocation in layout["allocations"] if allocation["memory"] != "APP"
    ]
    if app_allocations:
        app_block = generate_static_sections({"allocations": app_allocations})
        marker = "  __end = .;"
        if marker not in text:
            raise LayoutError("linker script is missing __end marker")
        text = text.replace(marker, app_block + "\n" + marker, 1)
    if external_allocations:
        external_block = generate_static_sections({"allocations": external_allocations})
        marker = "  /DISCARD/ :"
        if marker not in text:
            raise LayoutError("linker script is missing /DISCARD/ marker")
        text = text.replace(marker, external_block + "\n" + marker, 1)

    for blob in document.get("command_blobs", []):
        section = str(blob["section"])
        address = str(blob["address"])
        pattern = re.compile(rf"^  {re.escape(section)}\s*:\s*$", re.MULTILINE)
        text, count = pattern.subn(f"  {section} {address} :", text, count=1)
        if count == 0:
            raise LayoutError(f"linker script is missing command blob section {section}")
    return text


def write_raw_header(path: Path, document: dict[str, Any]) -> None:
    layout = normalize_layout(document)
    write_if_changed(path, generate_raw_header(layout))


def write_key_header(path: Path, document: dict[str, Any]) -> None:
    layout = normalize_layout(document)
    write_if_changed(path, generate_key_header(layout))
