// Generated by host_app/ui_designer from ui_layout.json. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

#include "middleware/ui/widget.hpp"
#include "ui_layout_images.hpp"

namespace uai::ai::app_ui {

inline constexpr std::uint16_t kScreenWidth = 800U;
inline constexpr std::uint16_t kScreenHeight = 480U;

enum class ScreenId : std::uint16_t {
    kMain = 0U,
    kMenu = 1U,
};

enum class WidgetId : std::uint16_t {
    kStatus = 1U,
    kOpenMenu = 2U,
    kCloseMenu = 3U,
    kMenuTitle = 4U,
    kLogo = 5U,
    kPerson = 6U,
    kFace = 7U,
    kSegmentation = 8U,
    kToggleBoxes = 9U,
    kMinConfidence = 10U,
    kStatusPeriod = 11U,
    kModelsCaption = 12U,
    kModels = 13U,
    kPersonRate = 14U,
    kDetections = 15U,
    kModelsPrev = 16U,
    kModelsNext = 17U,
    kNav = 18U,
};

inline constexpr ui::ButtonSpec kMainButtons[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kOpenMenu),
        {736U, 0U, 64U, 64U},
        "",
        {
            ui::Rgb565(0x00U, 0x00U, 0x00U),
            ui::Rgb565(0x40U, 0x40U, 0x40U),
            ui::Rgb565(0x00U, 0x00U, 0x00U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
            0U,
        },
        ui::Icon::kMenu,
        ui::Shape::kRectangle,
    },
};

inline constexpr ui::LabelSpec kMainLabels[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kStatus),
        {0U, 0U, 736U, 64U},
        "AI STARTING",
        {
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0x00U, 0x00U, 0x00U),
            true,
            2U,
            ui::TextAlign::kLeft,
            16U,
        },
    },
};

inline constexpr const char *const kModelsItems[] = {
    "ALL",
    "PERSON",
    "FACE",
    "SEG",
    "PERSON+FACE",
};

inline constexpr ui::ButtonSpec kMenuButtons[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kCloseMenu),
        {16U, 16U, 56U, 56U},
        "",
        {
            ui::Rgb565(0x10U, 0x18U, 0x20U),
            ui::Rgb565(0x30U, 0x40U, 0x50U),
            ui::Rgb565(0x10U, 0x18U, 0x20U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
            2U,
        },
        ui::Icon::kBack,
        ui::Shape::kEllipse,
    },
    {
        static_cast<std::uint16_t>(WidgetId::kPerson),
        {24U, 88U, 164U, 56U},
        "PERSON",
        {
            ui::Rgb565(0x40U, 0x40U, 0x40U),
            ui::Rgb565(0x20U, 0x20U, 0x20U),
            ui::Rgb565(0xC0U, 0x20U, 0x20U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            3U,
            2U,
        },
        ui::Icon::kNone,
        ui::Shape::kRounded,
    },
    {
        static_cast<std::uint16_t>(WidgetId::kFace),
        {220U, 88U, 164U, 56U},
        "FACE",
        {
            ui::Rgb565(0x40U, 0x40U, 0x40U),
            ui::Rgb565(0x20U, 0x20U, 0x20U),
            ui::Rgb565(0x20U, 0x40U, 0xC0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            3U,
            2U,
        },
        ui::Icon::kNone,
        ui::Shape::kRounded,
    },
    {
        static_cast<std::uint16_t>(WidgetId::kSegmentation),
        {416U, 88U, 164U, 56U},
        "SEG",
        {
            ui::Rgb565(0x40U, 0x40U, 0x40U),
            ui::Rgb565(0x20U, 0x20U, 0x20U),
            ui::Rgb565(0x20U, 0xA0U, 0x40U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            3U,
            2U,
        },
        ui::Icon::kNone,
        ui::Shape::kRounded,
    },
    {
        static_cast<std::uint16_t>(WidgetId::kToggleBoxes),
        {612U, 88U, 164U, 56U},
        "BOXES",
        {
            ui::Rgb565(0x40U, 0x40U, 0x40U),
            ui::Rgb565(0x20U, 0x20U, 0x20U),
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            3U,
            2U,
        },
        ui::Icon::kNone,
        ui::Shape::kPill,
    },
    {
        static_cast<std::uint16_t>(WidgetId::kModelsPrev),
        {264U, 288U, 56U, 56U},
        "",
        {
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0x10U, 0x30U, 0x60U),
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
            2U,
        },
        ui::Icon::kNone,
        ui::Shape::kTriangleLeft,
    },
    {
        static_cast<std::uint16_t>(WidgetId::kModelsNext),
        {264U, 368U, 56U, 56U},
        "",
        {
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0x10U, 0x30U, 0x60U),
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
            2U,
        },
        ui::Icon::kNone,
        ui::Shape::kTriangleRight,
    },
};

inline constexpr ui::LabelSpec kMenuLabels[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kMenuTitle),
        {88U, 24U, 400U, 40U},
        "SETTINGS",
        {
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            0U,
            false,
            4U,
            ui::TextAlign::kLeft,
            0U,
        },
    },
    {
        static_cast<std::uint16_t>(WidgetId::kModelsCaption),
        {24U, 248U, 200U, 24U},
        "MODELS",
        {
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            0U,
            false,
            2U,
            ui::TextAlign::kLeft,
            0U,
        },
    },
};

inline constexpr ui::SliderSpec kMenuSliders[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kMinConfidence),
        {24U, 168U, 480U, 72U},
        "MIN CONFIDENCE %",
        0, 100, 5, 50,
        {
            ui::Rgb565(0x30U, 0x40U, 0x50U),
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
            true,
        },
    },
};

inline constexpr ui::DialSpec kMenuDials[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kStatusPeriod),
        {568U, 176U, 208U, 232U},
        "STATUS MS",
        100, 2000, 100, 500,
        {
            ui::Rgb565(0x20U, 0x28U, 0x30U),
            ui::Rgb565(0x30U, 0x40U, 0x50U),
            ui::Rgb565(0x20U, 0xA0U, 0x60U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
            true,
        },
    },
};

inline constexpr ui::WheelSpec kMenuWheels[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kModels),
        {24U, 280U, 224U, 144U},
        kModelsItems, sizeof(kModelsItems) / sizeof(kModelsItems[0]), 0U,
        {
            ui::Rgb565(0x18U, 0x20U, 0x28U),
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0x80U, 0x90U, 0xA0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
        },
    },
};

inline constexpr ui::NumberSpec kMenuNumbers[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kPersonRate),
        {24U, 440U, 256U, 32U},
        "PERSON FPS",
        "",
        1U,
        0,
        {
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            0U,
            false,
            2U,
            ui::TextAlign::kLeft,
        },
    },
    {
        static_cast<std::uint16_t>(WidgetId::kDetections),
        {344U, 440U, 160U, 32U},
        "DET",
        "",
        0U,
        0,
        {
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            0U,
            false,
            2U,
            ui::TextAlign::kLeft,
        },
    },
};

inline constexpr ui::ImageSpec kMenuImages[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kLogo),
        {670U, 16U, 114U, 54U},
        kLogoPixels,
        true, 0xF81FU,
    },
};

inline constexpr ui::PadSpec kMenuPads[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kNav),
        {344U, 264U, 160U, 160U},
        true,
        {
            ui::Rgb565(0x30U, 0x30U, 0x30U),
            ui::Rgb565(0x60U, 0x60U, 0x60U),
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            2U,
        },
    },
};

/* Indexed by ScreenId. */
inline constexpr ui::ScreenSpec kScreens[] = {
    {
        static_cast<std::uint16_t>(ScreenId::kMain),
        ui::Background::kCamera, 0U,
        kMainButtons, sizeof(kMainButtons) / sizeof(kMainButtons[0]),
        kMainLabels, sizeof(kMainLabels) / sizeof(kMainLabels[0]),
        nullptr, 0U,
        nullptr, 0U,
        nullptr, 0U,
        nullptr, 0U,
        nullptr, 0U,
        nullptr, 0U,
    },
    {
        static_cast<std::uint16_t>(ScreenId::kMenu),
        ui::Background::kSolid, ui::Rgb565(0x10U, 0x18U, 0x20U),
        kMenuButtons, sizeof(kMenuButtons) / sizeof(kMenuButtons[0]),
        kMenuLabels, sizeof(kMenuLabels) / sizeof(kMenuLabels[0]),
        kMenuSliders, sizeof(kMenuSliders) / sizeof(kMenuSliders[0]),
        kMenuDials, sizeof(kMenuDials) / sizeof(kMenuDials[0]),
        kMenuWheels, sizeof(kMenuWheels) / sizeof(kMenuWheels[0]),
        kMenuNumbers, sizeof(kMenuNumbers) / sizeof(kMenuNumbers[0]),
        kMenuImages, sizeof(kMenuImages) / sizeof(kMenuImages[0]),
        kMenuPads, sizeof(kMenuPads) / sizeof(kMenuPads[0]),
    },
};
inline constexpr std::size_t kScreenCount =
    sizeof(kScreens) / sizeof(kScreens[0]);

/* Handler methods the application must provide on its Handlers type:
 *   void OnFaceTap(const ui::Event &event);
 *   void OnMinConfidenceChange(const ui::Event &event);
 *   void OnModelsChange(const ui::Event &event);
 *   void OnModelsNextTap(const ui::Event &event);
 *   void OnModelsPrevTap(const ui::Event &event);
 *   void OnNavRotate(const ui::Event &event);
 *   void OnNavTap(const ui::Event &event);
 *   void OnPersonTap(const ui::Event &event);
 *   void OnSegmentationTap(const ui::Event &event);
 *   void OnStatusPeriodChange(const ui::Event &event);
 *   void OnToggleBoxesTap(const ui::Event &event);
 *   void ShowScreen(ScreenId screen);
 */
template <typename Handlers>
bool Dispatch(Handlers &handlers, const ui::Event &event)
{
    if (event.type == ui::EventType::kTap) {
        switch (static_cast<WidgetId>(event.widget_id)) {
        case WidgetId::kOpenMenu:
            handlers.ShowScreen(ScreenId::kMenu);
            return true;
        case WidgetId::kCloseMenu:
            handlers.ShowScreen(ScreenId::kMain);
            return true;
        case WidgetId::kPerson:
            handlers.OnPersonTap(event);
            return true;
        case WidgetId::kFace:
            handlers.OnFaceTap(event);
            return true;
        case WidgetId::kSegmentation:
            handlers.OnSegmentationTap(event);
            return true;
        case WidgetId::kToggleBoxes:
            handlers.OnToggleBoxesTap(event);
            return true;
        case WidgetId::kModelsPrev:
            handlers.OnModelsPrevTap(event);
            return true;
        case WidgetId::kModelsNext:
            handlers.OnModelsNextTap(event);
            return true;
        case WidgetId::kNav:
            handlers.OnNavTap(event);
            return true;
        default:
            break;
        }
    }
    if (event.type == ui::EventType::kChange) {
        switch (static_cast<WidgetId>(event.widget_id)) {
        case WidgetId::kMinConfidence:
            handlers.OnMinConfidenceChange(event);
            return true;
        case WidgetId::kStatusPeriod:
            handlers.OnStatusPeriodChange(event);
            return true;
        case WidgetId::kModels:
            handlers.OnModelsChange(event);
            return true;
        case WidgetId::kNav:
            handlers.OnNavRotate(event);
            return true;
        default:
            break;
        }
    }
    return false;
}

} // namespace uai::ai::app_ui
