// Generated by host_app/ui_designer from ui_layout.json. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

#include "middleware/ui/widget.hpp"

namespace uai::ai::app_ui {

inline constexpr std::uint16_t kScreenWidth = 800U;
inline constexpr std::uint16_t kScreenHeight = 480U;

enum class WidgetId : std::uint16_t {
    kToggleBoxes = 1U,
};

inline constexpr ui::ButtonSpec kButtons[] = {
    {
        static_cast<std::uint16_t>(WidgetId::kToggleBoxes),
        {624U, 392U, 160U, 72U},
        "BOXES",
        {
            ui::Rgb565(0x20U, 0x60U, 0xC0U),
            ui::Rgb565(0x10U, 0x30U, 0x60U),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            ui::Rgb565(0xFFU, 0xFFU, 0xFFU),
            3U,
            2U,
        },
    },
};
inline constexpr std::size_t kButtonCount =
    sizeof(kButtons) / sizeof(kButtons[0]);

/* Handler methods the application must provide on its Handlers type:
 *   void OnToggleBoxesTap(const ui::Event &event);
 */
template <typename Handlers>
bool Dispatch(Handlers &handlers, const ui::Event &event)
{
    if (event.type == ui::EventType::kTap) {
        switch (static_cast<WidgetId>(event.widget_id)) {
        case WidgetId::kToggleBoxes:
            handlers.OnToggleBoxesTap(event);
            return true;
        default:
            break;
        }
    }
    return false;
}

} // namespace uai::ai::app_ui
