/* Generated by tools/generate_memory_layout.py. Do not edit. */

#ifndef UAI_AI_STATIC_MEMORY_LAYOUT_RAW_HPP
#define UAI_AI_STATIC_MEMORY_LAYOUT_RAW_HPP

#include <cstdint>

#include "type.hpp"

namespace uai::ai::static_memory_layout {

enum class Key : std::uint8_t {
    kThreadMonitor,
    kCapture0,
    kCapture1,
    kDisplay0,
    kDisplay1,
    kInference0,
    kInference1,
    kInference2,
    kInferenceScratch,
    kInferenceSource0,
    kInferenceSource1,
    kInferenceSource2,
    kRawDump,
    kSegmentationMask0,
    kSegmentationMask1,
    kPipe2Drop,
    kCount,
};

} // namespace uai::ai::static_memory_layout

extern "C" {
extern std::uint8_t __sample_ai_thread_monitor_start__[];
extern std::uint8_t __sample_ai_thread_monitor_end__[];
extern std::uint8_t __sample_ai_capture0_start__[];
extern std::uint8_t __sample_ai_capture0_end__[];
extern std::uint8_t __sample_ai_capture1_start__[];
extern std::uint8_t __sample_ai_capture1_end__[];
extern std::uint8_t __sample_ai_display0_start__[];
extern std::uint8_t __sample_ai_display0_end__[];
extern std::uint8_t __sample_ai_display1_start__[];
extern std::uint8_t __sample_ai_display1_end__[];
extern std::uint8_t __sample_ai_inference0_start__[];
extern std::uint8_t __sample_ai_inference0_end__[];
extern std::uint8_t __sample_ai_inference1_start__[];
extern std::uint8_t __sample_ai_inference1_end__[];
extern std::uint8_t __sample_ai_inference2_start__[];
extern std::uint8_t __sample_ai_inference2_end__[];
extern std::uint8_t __sample_ai_inference_scratch_start__[];
extern std::uint8_t __sample_ai_inference_scratch_end__[];
extern std::uint8_t __sample_ai_inference_source0_start__[];
extern std::uint8_t __sample_ai_inference_source0_end__[];
extern std::uint8_t __sample_ai_inference_source1_start__[];
extern std::uint8_t __sample_ai_inference_source1_end__[];
extern std::uint8_t __sample_ai_inference_source2_start__[];
extern std::uint8_t __sample_ai_inference_source2_end__[];
extern std::uint8_t __sample_ai_raw_dump_start__[];
extern std::uint8_t __sample_ai_raw_dump_end__[];
extern std::uint8_t __sample_ai_segmentation_mask0_start__[];
extern std::uint8_t __sample_ai_segmentation_mask0_end__[];
extern std::uint8_t __sample_ai_segmentation_mask1_start__[];
extern std::uint8_t __sample_ai_segmentation_mask1_end__[];
extern std::uint8_t __sample_ai_pipe2_drop_start__[];
extern std::uint8_t __sample_ai_pipe2_drop_end__[];
}

namespace uai::ai::static_memory_layout {

/* Addresses and capacities are emitted from one layout definition so
 * the allocator cannot silently diverge from the linker map. */
inline constexpr Layout<static_cast<std::size_t>(Key::kCount)> kLayout = {
    {{
        {__sample_ai_thread_monitor_start__, __sample_ai_thread_monitor_end__},
        {__sample_ai_capture0_start__, __sample_ai_capture0_end__},
        {__sample_ai_capture1_start__, __sample_ai_capture1_end__},
        {__sample_ai_display0_start__, __sample_ai_display0_end__},
        {__sample_ai_display1_start__, __sample_ai_display1_end__},
        {__sample_ai_inference0_start__, __sample_ai_inference0_end__},
        {__sample_ai_inference1_start__, __sample_ai_inference1_end__},
        {__sample_ai_inference2_start__, __sample_ai_inference2_end__},
        {__sample_ai_inference_scratch_start__, __sample_ai_inference_scratch_end__},
        {__sample_ai_inference_source0_start__, __sample_ai_inference_source0_end__},
        {__sample_ai_inference_source1_start__, __sample_ai_inference_source1_end__},
        {__sample_ai_inference_source2_start__, __sample_ai_inference_source2_end__},
        {__sample_ai_raw_dump_start__, __sample_ai_raw_dump_end__},
        {__sample_ai_segmentation_mask0_start__, __sample_ai_segmentation_mask0_end__},
        {__sample_ai_segmentation_mask1_start__, __sample_ai_segmentation_mask1_end__},
        {__sample_ai_pipe2_drop_start__, __sample_ai_pipe2_drop_end__},
    }},
};

} // namespace uai::ai::static_memory_layout

#endif // UAI_AI_STATIC_MEMORY_LAYOUT_RAW_HPP
