/*
 * The CubeMX-generated FSBL leaves EXTMEM_LRUN_SOURCE_SIZE at zero because
 * its example application uses a project-specific size.  experiment-ai's LRUN
 * payload is generated by CMake, so provide a fixed upper bound that covers
 * the current application image while staying below the next external-flash
 * allocation (the NPU command blobs at 0x70500000).
 */

#include <stdint.h>

uint32_t BOOT_GetApplicationSize(uint32_t image_address)
{
    (void)image_address;
    return 0x00080000U;
}
